#!/bin/bash
# Various containers work under different UID/GUID
# be reckless and make those directories world readable
# NOT A PRODUCTION SETUP!

sudo mkdir -p data/elastic
sudo chmod a+rwX data/elastic
sudo mkdir -p logs/elastic
sudo chmod a+rwX logs/elastic
sudo mkdir -p data/mysql
sudo chmod a+rwX data/mysql
